# Generated by Django 4.2 on 2024-01-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
